FROM nousresearch/hermes-agent:latest

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Create writable dirs
RUN mkdir -p /run /tmp && chmod 1777 /run /tmp

ENTRYPOINT ["/entrypoint.sh"]
